Exit on error in clang-setup script.

diff --git a/scripts/clang-setup b/scripts/clang-setup
--- a/scripts/clang-setup
+++ b/scripts/clang-setup
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# exit on error
+set -e
+
 if ! command -v sudo &> /dev/null; then
   SUDO='' # sudo doesn't exist
 else
